### PR TITLE
Create run engine

### PR DESCRIPTION
**Pull request by Tom-Willemsen**
Create a run engine, and add basic tests for run engine functionality.

https://github.com/ISISComputingGroup/ibex_bluesky_core/issues/2

To review:
- Check demo plan works
- Check tests & linting pass (this will soon be done by CI, but as CI is not merged yet, it needs to be checked manually)
- Check as a developer you agree with the initial basic set of tests for bluesky run engine functionality (the goal is not to exhaustively test it, but to check we've configured it in a sane way)
- Check as a developer basic interactive run engine functionality works - e.g. run a plan, interrupt it, add a custom callback, etc.

Notes:
- The custom `_DuringTask` has been pushed upstream (https://github.com/bluesky/bluesky/pull/1770); if & when that PR gets merged & released we can remove our version

### CODE REVIEW

**Comment by iangillingham-stfc** [comment]
Everything this looks pretty good and all tests look valid and pass. I just have a couple of points/questions that cropped up in my review:
1) I question the instance naming of the RunEngine class as "RE". It flies in the face of PEP-8 and is also the same name as the 're' module (regular expressions), apart from the case.
2) I struggled to see how a single instance of the RunEngine was guaranteed to be singleton - I'm assuming it's the @cache decorator that's producing this effect? Did you consider creating a true singleton subclass of RunEngine?

Otherwise, the code is really tidy and well documented.

**Review by iangillingham-stfc — DISMISSED** [review]
Very tidy and well documented. I left some comments in the PR, but nothing that should prevent this being merged.

**Comment by Tom-Willemsen** [comment]
As discussed in person:

> I question the instance naming of the RunEngine class as "RE". It flies in the face of PEP-8 and is also the same name as the 're' module (regular expressions), apart from the case.

The thought was to follow the bluesky conventions here, e.g. the [docs, tutorial](https://nsls-ii.github.io/bluesky/tutorial.html) and most other bluesky facilities use `RE` for their runengines.

> I struggled to see how a single instance of the RunEngine was guaranteed to be singleton - I'm assuming it's the `@cache` decorator that's producing this effect? Did you consider creating a true singleton subclass of RunEngine?

Comment added to further clarify the existing docstring on the function.

**Review by iangillingham-stfc — DISMISSED** [review]
The documented explanation of the use of @cache has clarified the get_run_engine() function returning a singleton.

**Review by iangillingham-stfc — APPROVED** [review]
Looks good. All tests in place and pass.

**Pull request merged**
