### PR TITLE
Add IBEX plotting callback

### PR DESCRIPTION
**Pull request by Tom-Willemsen**
https://github.com/ISISComputingGroup/ibex_bluesky_core/issues/8

### Docs
- [ ] Ensure docs give enough information/pointers to documentation elsewhere for users to find out how to configure plots.
- [ ] Ensure all the points in the ticket's acceptance criteria have been met.

### To test this in a standalone session:
- Ensure you are in the `ibex_bluesky_core` venv as per dev setup notes.
- Ensure you have recently re-run `python -m pip install -e .[dev]` to pick up matplotlib and qt dependencies
- Run `python src\ibex_bluesky_core\demo_plan.py`
- [x] A matplotlib `Qt` window should appear and be updated live during the plan.
- [x] A long running plan like `bps.sleep(999)` should be interruptible via `ctrl-c`.

### To test this within the IBEX gui:
- Rebuild your `genie_python` using the branch linked from https://github.com/ISISComputingGroup/IBEX/issues/8453
- Run `c:\instrument\apps\python3\python.exe -m pip install -e c:\instrument\dev\ibex_bluesky_core\`
  * This installs `ibex_bluesky_core` into your genie_python environment (not a `.venv`)
- Ensure IBEX is set up with blocks and DAE as per existing dev setup notes.
- In the IBEX pydev scripting console run:
```python
from ibex_bluesky_core.run_engine import get_run_engine
from ibex_bluesky_core.demo_plan import demo_plan
RE = get_run_engine()
RE(demo_plan())
```
- [x] A matplotlib window should appear and be updated live during the plan.
- [ ] A long running plan like `bps.sleep(999)` should be interruptible via `ctrl-c`.

### CODE REVIEW

**Comment by jackbdoughty** [comment]
Looks good to me, plotting works as expected. One thing I have noticed though is that when you pause (Ctrl + C) a plan for the second time, in the pydev console, this causes an exception and I can't resume the plan again. Not sure if this is intentional or just on my machine? Also not sure how relevant this is to this ticket but think its worth saying.
 `Exception in thread Thread-6 (maybe_prompt_pause):
Traceback (most recent call last):
  File "C:\Instrument\Apps\Python3\Lib\threading.py", line 1045, in _bootstrap_inner
    self.run()
  File "C:\Instrument\Apps\Python3\Lib\threading.py", line 982, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Instrument\Apps\Python3\Lib\site-packages\bluesky\utils\__init__.py", line 291, in maybe_prompt_pause
    self.RE.request_pause(False)
  File "C:\Instrument\Apps\Python3\Lib\site-packages\bluesky\run_engine.py", line 817, in request_pause
    return future.result()
           ^^^^^^^^^^^^^^^
  File "C:\Instrument\Apps\Python3\Lib\concurrent\futures\_base.py", line 456, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Instrument\Apps\Python3\Lib\concurrent\futures\_base.py", line 401, in __get_result
    raise self._exception
  File "C:\Instrument\Apps\Python3\Lib\site-packages\bluesky\run_engine.py", line 835, in _request_pause_coro
    current_run.record_interruption("pause")
  File "C:\Instrument\Apps\Python3\Lib\site-packages\bluesky\bundlers.py", line 449, in record_interruption
    doc = self._interruptions_compose_event(
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Instrument\Apps\Python3\Lib\site-packages\event_model\__init__.py", line 2312, in __call__
    seq_num = self.event_counters[self.descriptor["name"]]
              ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^
KeyError: 'interruptions'`

**Comment by Tom-Willemsen** [comment]
@jackbdoughty can you check you have a recent GUI build? Pull main and run `build.bat` or update target platform in eclipse...

**Comment by jackbdoughty** [comment]
It also might just be worth making it clearer to the user to do `from ibex_bluesky_core.run_engine import get_run_engine
RE = get_run_engine()` to be able to call `RE.resume()`. As right now the message received after doing a ctrl + c is `Your RunEngine is entering a paused state. These are your options for changing
the state of the RunEngine:

RE.resume()    Resume the plan.
RE.abort()     Perform cleanup, then kill plan. Mark exit_stats='aborted'.
RE.stop()      Perform cleanup, then kill plan. Mark exit_status='success'.
RE.halt()      Emergency Stop: Do not perform cleanup --- just stop.`

**Comment by Tom-Willemsen** [comment]
Yeah that's a difference between `run_demo_plan` and `demo_plan` really.

I think the direction of travel is that IBEX will automatically create a `RunEngine` (by calling `RE = get_run_engine()`) as one of the standard GUI initialization commands - like we already have for setting matplotlib backends etc.

So then at the user level they _would_ have access to the RE, and would be executing plans with something like:
```python
RE(my_plan())
```
at the command-line.

Let's chat after lunch...

**Review by jackbdoughty — APPROVED** [review]

**Pull request merged**
